spring:
  application:
    name: minipay

  datasource:
    url: jdbc:postgresql://localhost:5432/minipay
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
