--- create users ---
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL 
);

--- create wallets ---
CREATE TABLE wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    balance DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_wallets_users
        FOREIGN KEY (user_id)
        REFERENCES users(id),
    
    CONSTRAINT chk_wallets_balance_non_negative
        CHECK (balance >= 0)
);

--- create transactions ---
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_wallet_id BIGINT,
    to_wallet_id BIGINT,
    amount DECIMAL(19, 2) NOT NULL,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_transactions_from_wallet
        FOREIGN KEY (from_wallet_id)
        REFERENCES wallets(id),
    
    CONSTRAINT fk_transactions_to_wallet
        FOREIGN KEY (to_wallet_id)
        REFERENCES wallets(id),
    
    CONSTRAINT chk_transactions_amount_non_negative
        CHECK (amount >= 0.01),
    
    CONSTRAINT chk_transactions_type
        CHECK (type IN ('DEPOSIT', 'TRANSFER', 'WITHDRAWAL')),
    
    CONSTRAINT chk_transactions_status
        CHECK (status IN ('CREATED', 'SUCCESS', 'FAILED'))
);

--- Create an index ---
CREATE INDEX idx_transactions_from_wallet_created_at
    ON transactions (from_wallet_id, created_at DESC);
    
CREATE INDEX idx_transactions_to_wallet_created_at
    ON transactions (to_wallet_id, created_at DESC);